#!/usr/bin/env python3
"""
Automated Session Logging Script

Creates dual-format session logs:
- Human-readable .log file
- Machine-readable .json file for automation

Usage:
    python scripts/create_session_log.py [--session-type "work|review|planning"]
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional


class SessionLogger:
    """Handles automated session logging with dual output formats."""

    def __init__(self, base_dir: Optional[Path] = None):
        self.base_dir = base_dir or Path.cwd()
        self.logs_dir = self.base_dir / "ai-logs" / "logs"
        self.sessions_dir = self.logs_dir / "sessions"
        self.ensure_directories()

    def ensure_directories(self):
        """Create logging directories if they don't exist."""
        self.sessions_dir.mkdir(parents=True, exist_ok=True)

    def create_session_log(self, session_type: str = "work") -> Dict[str, Any]:
        """Create a new session log entry."""
        timestamp = datetime.now()
        session_id = timestamp.strftime("%Y%m%d-%H%M%S")

        session_data = {
            "session_id": session_id,
            "timestamp": timestamp.isoformat(),
            "session_type": session_type,
            "git_branch": self.get_git_branch(),
            "git_commit": self.get_git_commit(),
            "working_directory": str(self.base_dir),
            "python_version": sys.version,
            "start_time": timestamp.isoformat(),
        }

        # Create both formats
        self._write_log_file(session_data)
        self._write_json_file(session_data)

        return session_data

    def get_git_branch(self) -> str:
        """Get current git branch."""
        try:
            import subprocess

            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                capture_output=True,
                text=True,
                check=True,
            )
            return result.stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return "unknown"

    def get_git_commit(self) -> str:
        """Get current git commit hash."""
        try:
            import subprocess

            result = subprocess.run(
                ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True
            )
            return result.stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return "unknown"

    def _write_log_file(self, session_data: Dict[str, Any]):
        """Write human-readable log file."""
        timestamp = datetime.fromisoformat(session_data["timestamp"])
        date_str = timestamp.strftime("%Y-%m-%d")
        filename = f"{date_str}_session-{session_data['session_id'][-6:]}.log"
        filepath = self.sessions_dir / filename

        log_content = f"""Session Log: {session_data["session_id"]}
{"=" * 50}
Date: {timestamp.strftime("%Y-%m-%d %H:%M:%S")}
Type: {session_data["session_type"]}
Directory: {session_data["working_directory"]}

Git Information:
- Branch: {session_data["git_branch"]}
- Commit: {session_data["git_commit"]}

Environment:
- Python: {session_data["python_version"]}

Session started at: {session_data["start_time"]}

Use this log to track:
- Work completed during the session
- Issues encountered and resolved
- Decisions made
- Next steps

---
This log was automatically generated by create_session_log.py
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(log_content)

        print(f"Created log file: {filepath}")

    def _write_json_file(self, session_data: Dict[str, Any]):
        """Write machine-readable JSON file."""
        timestamp = datetime.fromisoformat(session_data["timestamp"])
        date_str = timestamp.strftime("%Y-%m-%d")
        filename = f"{date_str}_session-{session_data['session_id'][-6:]}.json"
        filepath = self.sessions_dir / filename

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(session_data, f, indent=2, ensure_ascii=False)

        print(f"Created JSON file: {filepath}")

    def list_recent_sessions(self, limit: int = 10) -> list:
        """List recent session files."""
        sessions = []

        for log_file in sorted(self.sessions_dir.glob("*.json"), reverse=True):
            if len(sessions) >= limit:
                break

            try:
                with open(log_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    sessions.append(data)
            except (json.JSONDecodeError, FileNotFoundError):
                continue

        return sessions


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Create automated session logs")
    parser.add_argument(
        "--session-type",
        choices=["work", "review", "planning", "debug"],
        default="work",
        help="Type of session being logged",
    )
    parser.add_argument("--list", action="store_true", help="List recent sessions")
    parser.add_argument(
        "--base-dir",
        type=Path,
        help="Base directory for logs (default: current directory)",
    )

    args = parser.parse_args()

    logger = SessionLogger(args.base_dir)

    if args.list:
        sessions = logger.list_recent_sessions()
        if sessions:
            print("Recent sessions:")
            for session in sessions:
                timestamp = datetime.fromisoformat(session["timestamp"])
                print(
                    f"  {session['session_id']} - {timestamp.strftime('%Y-%m-%d %H:%M')} ({session['session_type']})"
                )
        else:
            print("No recent sessions found.")
    else:
        session_data = logger.create_session_log(args.session_type)
        print(f"Session {session_data['session_id']} logged successfully!")


if __name__ == "__main__":
    main()
